apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: development
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  namespace: development
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-sms
  namespace: development
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-sms
  namespace: development
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twilio-sms
  namespace: development
spec:
  replicas: 2
