apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki-gateway.monitoring.svc.cluster.local:80
    jsonData:
      maxLines: 1000
    editable: false