apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo.monitoring.svc.cluster.local:3200
    jsonData:
      serviceGraphs:
        datasourceUid: 'prometheus'
      metrics:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod']
        filterByTraceId: true
        filterBySpanId: false
    editable: false