
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-project
  namespace: argocd
spec:
  description: Skeleton for springservice project
  sourceRepos:
    - https://github.com/SodiqIshola/springservice.git
    - https://prometheus-community.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
    - https://grafana-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    # Common namespaces allowed in all environments
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
